    
server:
  port: 8013
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/ #defaultZone不能写成default-zone,否则无法注册服务